version: '2'
services:
    keycloak-server:
        container_name: keycloak-server
        image: jboss/keycloak
        external_links:
            - keycloak-mysql:mysql
        environment:
            - MYSQL_DATABASE=openiot
            - MYSQL_USER=openiot
            - MYSQL_PASSWORD=openiot
            - KEYCLOAK_LOGLEVEL=DEBUG jboss/keycloak
        ports:
            - 8181:8080
        volumes:
            - ./keycloak-server/user/keycloak-add-user.json:/opt/jboss/keycloak/standalone/configuration/keycloak-add-user.json
            - ./keycloak-server/cli-scripts:/cli-scripts
            - ./keycloak-server/drop-ins:/drop-ins
        restart: unless-stopped
    keycloak-mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: openiot
      MYSQL_DATABASE: openiot
    volumes_from:
      - mysqldata
  mysqldata:
    image: ubuntu
    volumes:
      - "/persistence/mysqldb:/var/lib/mysql"
    command: echo Persistence for MySql
  keycloak-mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1080:1080