version: '2'
services:
    keycloak-server:
      extends:
        file: keycloak-server.yml
        service: keycloak-server
      links:
        - keycloak-mailcatcher:mailcatcher
      external_links:
        - keycloak-mysql:mysql
      volumes:
        - ./keycloak-server:/keycloak-server
    keycloak-mailcatcher:
      image: schickling/mailcatcher
      ports:
        - 1080:1080
    keycloak-mysql:
      image: mysql
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: openiot
        MYSQL_DATABASE: openiot
        MYSQL_PASSWORD: openiot
        MYSQL_USER: openiot 
      volumes_from:
        - mysqldata
    mysqldata:
      image: ubuntu
      volumes:
        - "/persistence/mysqldb:/var/lib/mysql"
      command: echo Persistence for MySql
