version: '2'
services:
    keycloak-server:
        container_name: keycloak-server
        image: jboss/keycloak
        external_links:
            - keycloak-mysql:mysql
        environment:
            - MYSQL_DATABASE=openiot
            - MYSQL_USER=openiot
            - MYSQL_PASSWORD=openiot
            - MYSQL_PORT_3306_TCP_ADDR=keycloak-mysql
            - MYSQL_PORT_3306_TCP_PORT=3306
        ports:
            - 8181:8080
        volumes:
            - ./keycloak-server/user/keycloak-add-user.json:/opt/jboss/keycloak/standalone/configuration/keycloak-add-user.json
            - ./keycloak-server/cli-scripts:/cli-scripts
            - ./keycloak-server/drop-ins:/drop-ins
        restart: unless-stopped
