version: '2'
services:
  keycloak-mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: openiot
      MYSQL_DATABASE: openiot
    volumes_from:
      - mysqldata
  mysqldata:
    image: ubuntu
    volumes:
      - "/persistence/mysqldb:/var/lib/mysql"
    command: echo Persistence for MySql